
import { PracticeTurn } from "./practice";

export type QuestionCategory = 'Business' | 'Social' | 'Academic' | 'Travel' | 'Philosophical' | 'Abstract';

export const PRACTICE_QUESTIONS: (PracticeTurn & { complexity: 'simple' | 'moderate' | 'complex'; category: QuestionCategory })[] = [
    // --- BUSINESS (Moderate / Complex) ---
    {
        id: "biz-1",
        type: "ROLEPLAY",
        situation: "Job Interview",
        difficulty: 3,
        complexity: "complex",
        category: "Business",
        prompt: "Tell me about a time you had to deal with a difficult colleague. How did you handle it?",
    },
    {
        id: "biz-2",
        type: "EXPLANATION",
        situation: "Meeting",
        difficulty: 3,
        complexity: "complex",
        category: "Business",
        prompt: "Explain the concept of 'remote work culture' to a traditional manager. What are the pros and cons?",
    },
    {
        id: "biz-3",
        type: "OPINION",
        situation: "Strategy",
        difficulty: 2,
        complexity: "moderate",
        category: "Business",
        prompt: "Is it better to specialize in one skill or be a generalist? Why?",
    },
    {
        id: "biz-4",
        type: "ROLEPLAY",
        situation: "Sales",
        difficulty: 2,
        complexity: "moderate",
        category: "Business",
        prompt: "Persuade a potential client to try a new product they didn't ask for.",
    },
    {
        id: "biz-5",
        type: "DEBATE",
        situation: "Workplace",
        difficulty: 3,
        complexity: "complex",
        category: "Business",
        prompt: "Should companies monitor employee productivity with software? Argue your stance.",
    },

    // --- SOCIAL (Simple / Moderate) ---
    {
        id: "soc-1",
        type: "STORYTELLING",
        situation: "Dinner Party",
        difficulty: 2,
        complexity: "moderate",
        category: "Social",
        prompt: "Tell a funny story about a cooking disaster or a bad meal you had.",
    },
    {
        id: "soc-2",
        type: "OPINION",
        situation: "Friendship",
        difficulty: 2,
        complexity: "moderate",
        category: "Social",
        prompt: "What makes a good friend? Describe the most important quality.",
    },
    {
        id: "soc-3",
        type: "LISTEN_REACT",
        situation: "Networking",
        difficulty: 1,
        complexity: "simple",
        category: "Social",
        prompt: "Someone introduces themselves: 'Hi, I'm new here and I don't know anyone.' Respond warmly.",
    },
    {
        id: "soc-4",
        type: "QUICK_RESPONSE",
        situation: "Casual",
        difficulty: 1,
        complexity: "simple",
        category: "Social",
        prompt: "What is your favorite way to spend a rainy Sunday?",
    },
    {
        id: "soc-5",
        type: "PICK_SPEAK",
        situation: "Icebreaker",
        difficulty: 1,
        complexity: "simple",
        category: "Social",
        prompt: "Which is better? Movies or Books? Pick one and explain why in 2 sentences.",
        choices: ["Movies", "Books"]
    },

    // --- ACADEMIC / INTELLECTUAL (Complex) ---
    {
        id: "acad-1",
        type: "DEBATE",
        situation: "Education",
        difficulty: 3,
        complexity: "complex",
        category: "Academic",
        prompt: "Is university education still necessary for success in the modern world?",
    },
    {
        id: "acad-2",
        type: "EXPLANATION",
        situation: "Science",
        difficulty: 3,
        complexity: "complex",
        category: "Academic",
        prompt: "Explain how Artificial Intelligence might change education in the next 10 years.",
    },
    {
        id: "acad-3",
        type: "FINISH_THOUGHT",
        situation: "Logic",
        difficulty: 2,
        complexity: "moderate",
        category: "Academic",
        prompt: "Complete this thought: 'History is important because only by understanding the past can we...'",
    },
    {
        id: "acad-4",
        type: "OPINION",
        situation: "Technology",
        difficulty: 3,
        complexity: "complex",
        category: "Academic",
        prompt: "Does technology make us more connected or more isolated? defend your view.",
    },

    // --- TRAVEL / CULTURAL (Moderate) ---
    {
        id: "trav-1",
        type: "STORYTELLING",
        situation: "Travel",
        difficulty: 2,
        complexity: "moderate",
        category: "Travel",
        prompt: "Describe the most beautiful place you have ever visited. Use sensory details.",
    },
    {
        id: "trav-2",
        type: "ROLEPLAY",
        situation: "Airport",
        difficulty: 2,
        complexity: "moderate",
        category: "Travel",
        prompt: "Your flight was cancelled. Politely but firmly ask the airline agent for a hotel voucher.",
    },
    {
        id: "trav-3",
        type: "OPINION",
        situation: "Culture",
        difficulty: 2,
        complexity: "moderate",
        category: "Travel",
        prompt: "Is it better to plan every detail of a trip or to be spontaneous? Why?",
    },
    {
        id: "trav-4",
        type: "EXPLANATION",
        situation: "Guidance",
        difficulty: 2,
        complexity: "moderate",
        category: "Travel",
        prompt: "Explain to a visitor why they should visit your home city.",
    },

    // --- PHILOSOPHICAL / ABSTRACT (Complex) ---
    {
        id: "phil-1",
        type: "OPINION",
        situation: "Ethics",
        difficulty: 3,
        complexity: "complex",
        category: "Philosophical",
        prompt: "Is it always right to tell the truth, even if it hurts someone's feelings?",
    },
    {
        id: "phil-2",
        type: "EXPLANATION",
        situation: "Life",
        difficulty: 3,
        complexity: "complex",
        category: "Philosophical",
        prompt: "What does 'success' mean to you personally?",
    },
    {
        id: "phil-3",
        type: "DEBATE",
        situation: "Future",
        difficulty: 3,
        complexity: "complex",
        category: "Philosophical",
        prompt: "If humans could live forever, would that be a blessing or a curse?",
    },
    {
        id: "phil-4",
        type: "FINISH_THOUGHT",
        situation: "Wisdom",
        difficulty: 2,
        complexity: "moderate",
        category: "Philosophical",
        prompt: "Finish this sentence: 'The biggest lesson I learned this year was...'",
    },

    // --- SIMPLE BASICS (Warmup) ---
    {
        id: "base-1",
        type: "QUICK_RESPONSE",
        situation: "Morning",
        difficulty: 1,
        complexity: "simple",
        category: "Social",
        prompt: "What is the first thing you do when you wake up?",
    },
    {
        id: "base-2",
        type: "OPINION",
        situation: "Food",
        difficulty: 1,
        complexity: "simple",
        category: "Social",
        prompt: "Do you prefer cooking at home or eating out?",
    },
    {
        id: "base-3",
        type: "LISTEN_REACT",
        situation: "Help",
        difficulty: 1,
        complexity: "simple",
        category: "Social",
        prompt: "Someone asks: 'Can you help me lift this box?' Respond appropriately.",
    },
    {
        id: "base-4",
        type: "STORYTELLING",
        situation: "Weekend",
        difficulty: 1,
        complexity: "simple",
        category: "Social",
        prompt: "What did you do last weekend?",
    }
];
